"""Chunk content size enforcement for the indexing pipeline.

Splits oversized chunks into smaller sub-chunks while preserving metadata.
This prevents failures in AlloyDB's ai.initialize_embeddings() which has a
4MB per-row request limit.
"""

from __future__ import annotations

import logging
from typing import List, Optional, Union

from agentic_inquiry.parsers.models import ParserChunk

logger = logging.getLogger(__name__)

# Minimum allowed max_size to prevent degenerate splitting
MIN_CHUNK_SIZE = 100


def split_parser_chunks(
    chunks: List[ParserChunk],
    max_size: int,
) -> List[ParserChunk]:
    """Split ParserChunk objects exceeding max_size into sub-chunks.

    Called in the indexing pipeline before embedding and storage.

    Strategy:
    1. Try splitting on paragraph boundaries (double newline)
    2. Fall back to single newline boundaries
    3. Fall back to hard split at max_size

    Sub-chunks inherit all parent fields except content and fts_text.

    Args:
        chunks: List of ParserChunk objects from parser output.
        max_size: Maximum content length in characters. Must be >= MIN_CHUNK_SIZE.

    Returns:
        New list with oversized chunks replaced by sub-chunks.
        Chunks within the limit are returned unchanged.
    """
    if max_size < MIN_CHUNK_SIZE:
        raise ValueError(f"max_size must be >= {MIN_CHUNK_SIZE}, got {max_size}")

    result: List[ParserChunk] = []
    split_count = 0

    for chunk in chunks:
        content = chunk.content or ""
        if len(content) <= max_size:
            result.append(chunk)
            continue

        logger.info(
            "Splitting oversized chunk (%d chars, max %d) from file context: %s",
            len(content),
            max_size,
            chunk.element_name or chunk.element_type or "unknown",
        )

        pieces = _split_content(content, max_size)
        split_count += 1

        for piece in pieces:
            sub_chunk = ParserChunk(
                content=piece,
                fts_text=None,  # Will be regenerated by downstream processing
                content_type=chunk.content_type,
                language=chunk.language,
                page_number=chunk.page_number,
                line_start=chunk.line_start,
                line_end=chunk.line_end,
                element_type=chunk.element_type,
                element_name=chunk.element_name,
                parent_id=chunk.parent_id,
                child_ids=chunk.child_ids,
                symbols=chunk.symbols,
                relationships=chunk.relationships,
                metadata=chunk.metadata,
                ranking_signals=chunk.ranking_signals,
                symbol_rankings=chunk.symbol_rankings,
            )
            result.append(sub_chunk)

        logger.info(
            "Split chunk into %d sub-chunks",
            len(pieces),
        )

    if split_count:
        logger.info(
            "Chunk splitting complete: %d oversized chunks split, %d → %d total",
            split_count,
            len(chunks),
            len(result),
        )

    return result


def _split_content(content: str, max_size: int) -> List[str]:
    """Split content string into pieces each <= max_size.

    Tries paragraph boundaries first, then line boundaries, then hard split.
    """
    # Try paragraph boundaries
    pieces = _split_on_separator(content, "\n\n", max_size)
    if pieces is not None:
        return pieces

    # Try line boundaries
    pieces = _split_on_separator(content, "\n", max_size)
    if pieces is not None:
        return pieces

    # Hard split as last resort
    return _hard_split(content, max_size)


def _split_on_separator(
    content: str,
    separator: str,
    max_size: int,
) -> Optional[List[str]]:
    """Try to split content on a separator, keeping pieces under max_size.

    Returns None if any individual segment exceeds max_size (meaning this
    separator granularity is insufficient).
    """
    segments = content.split(separator)

    # Check if all segments fit — if any single segment exceeds max_size,
    # this separator can't work
    for seg in segments:
        if len(seg) > max_size:
            return None

    pieces: List[str] = []
    current: List[str] = []
    current_len = 0

    for seg in segments:
        seg_len = len(seg)
        sep_len = len(separator) if current else 0
        new_len = current_len + sep_len + seg_len

        if new_len > max_size and current:
            pieces.append(separator.join(current))
            current = [seg]
            current_len = seg_len
        else:
            current.append(seg)
            current_len = new_len

    if current:
        pieces.append(separator.join(current))

    return pieces


def _hard_split(content: str, max_size: int) -> List[str]:
    """Split content at exact character boundaries as last resort."""
    pieces: List[str] = []
    for i in range(0, len(content), max_size):
        pieces.append(content[i : i + max_size])
    return pieces
