"""Content-hash LRU cache wrapper for ``Embedder`` implementations.

Indexing workloads frequently see duplicate embedding text — generated
files (autogenerated clients, protobuf stubs), vendored third-party
deps copied across monorepos, boilerplate like license headers, and
near-identical chunks from identical file paths in different branches
(branch indexing). Every duplicate runs the underlying model's forward
pass from scratch. For the default ``all-MiniLM-L6-v2`` model at 384
dims, each redundant call is ~5-50 ms of wasted compute depending on
device; across a 100k-chunk indexing run with 20% duplication that's
minutes of avoidable time.

``CachingEmbedder`` wraps any :class:`~agent_vault.embeddings.base.Embedder`
with a per-process LRU keyed on SHA256 of each text. Hit-rate depends
entirely on workload duplication — 0% on cleanroom repos, 20-30% on
typical monorepos, can exceed 50% on branch-indexing runs. It's a
pure win when it hits and cheap when it doesn't (a SHA256 + dict
lookup vs. a model forward pass is a no-contest bet).

Design notes:
- **LRU via ``OrderedDict``**: simple, avoids an ``lru_cache`` decorator
  because we need to cache per-item (not per-list), and the input
  ``list[str]`` isn't hashable. ``move_to_end`` makes recent hits
  survive eviction.
- **Compact numpy float32 storage**: cached vectors are stored as
  ``np.ndarray(dtype=np.float32)`` rather than ``list[float]``. Python
  lists of floats are deceptively expensive — each Python float is a
  24-byte object plus an 8-byte pointer in the list, so a 384-dim
  vector as ``list[float]`` is ~12 KB. As float32 bytes that drops to
  ~1.5 KB (4 bytes × ndims plus numpy header overhead). 10k entries
  at 384 dims: ~15 MB with float32 vs. ~120 MB with Python lists.
  Conversion back to ``list[float]`` on return happens once per hit
  (~microseconds for a 384-dim vector).
- **Thread safety**: the indexing pipeline calls ``generate`` through
  a thread-pool executor. Cache access + hit/miss counters are
  protected by a single lock; the underlying model call (the slow
  part) runs **outside** the lock.
- **In-batch dedup**: if the same text appears twice in one call, we
  only pass it to the underlying embedder once. Matters in practice
  for repos with a common license header at the top of many files
  (each file yields one chunk with that header) — before dedup we'd
  embed it N times per batch.
- **``ensure_model_loaded`` delegation**: warmup paths like
  ``EmbeddingService`` background preload expect to trigger the
  underlying model load. The cache wrapper forwards the call so
  callers see the same warmup semantics they had without caching.
- **Pass-through on empty input**: returns ``[]`` without touching the
  cache or underlying embedder.
"""
from __future__ import annotations

import hashlib
import logging
import threading
from collections import OrderedDict
from typing import List, Optional

import numpy as np

from agent_vault.embeddings.base import Embedder

logger = logging.getLogger(__name__)


class CachingEmbedder(Embedder):
    """Wraps another :class:`Embedder` with a content-hash LRU cache.

    Every text going through ``generate`` is hashed (SHA256 of the UTF-8
    bytes). A hit returns the cached vector without touching the
    underlying embedder. A miss passes only the uncached texts through,
    then stores their vectors.

    The underlying embedder is called at most once per unique uncached
    text per batch, so in-batch duplicates don't multiply model work.

    **Async callers benefit too.** The base class ``generate_async``
    default routes through ``self.generate`` in a ``ThreadPoolExecutor``,
    so ``await cached.generate_async(...)`` gets the same cache + in-batch
    dedup as the sync path — no separate code path to keep in sync.

    Example:
        >>> from agent_vault.embeddings.sentence_transformer import (
        ...     SentenceTransformerEmbedder,
        ... )
        >>> base = SentenceTransformerEmbedder()
        >>> cached = CachingEmbedder(base, max_entries=10_000)
        >>> vectors = cached.generate(["hello", "world", "hello"])
        >>> # "hello" hit the underlying embedder once; the second
        >>> # "hello" came from the intra-batch dedup.

    Attributes:
        hits: Total cache hits across all ``generate`` calls.
        misses: Total cache misses (computed by underlying embedder).
    """

    def __init__(self, wrapped: Embedder, max_entries: int = 10_000) -> None:
        """Wrap ``wrapped`` with a bounded LRU cache.

        Args:
            wrapped: Underlying embedder. Must implement
                :class:`Embedder` (``generate`` + ``ndims``).
            max_entries: Cache capacity in unique entries. Each entry
                is a 64-char SHA256 hex digest (64 bytes as a Python
                string plus interning overhead) plus one numpy float32
                vector (~1.5 KB at 384 dims, ~3 KB at 768, ~6 KB at
                1536) plus ``OrderedDict`` overhead. Default 10k fits
                comfortably in ~15 MB at 384 dims. Setting
                ``max_entries=0`` disables caching (pass-through).
        """
        if max_entries < 0:
            raise ValueError(f"max_entries must be >= 0, got {max_entries}")
        self._wrapped = wrapped
        self._max_entries = max_entries
        self._cache: "OrderedDict[str, np.ndarray]" = OrderedDict()
        self._lock = threading.Lock()
        self.hits = 0
        self.misses = 0

    def ensure_model_loaded(self) -> None:
        """Delegate to the wrapped embedder.

        ``EmbeddingService`` and other callers invoke this to warm up
        the underlying model out-of-band so the first indexing batch
        doesn't pay cold-start latency. The default ``Embedder``
        implementation is a no-op, so without this override the
        wrapped model would be loaded lazily on the first ``generate``
        call instead of during startup.
        """
        self._wrapped.ensure_model_loaded()

    def generate(self, texts: List[str]) -> List[List[float]]:
        if not texts:
            return []

        # Caching disabled: pass through.
        if self._max_entries == 0:
            return self._wrapped.generate(texts)

        # Hash each text to its cache key (SHA256 of UTF-8 bytes).
        keys = [hashlib.sha256(text.encode("utf-8")).hexdigest() for text in texts]

        # Cache hits are stored as numpy float32 arrays for compactness
        # (see module docstring). ``results`` holds the per-position
        # ``list[float]`` we'll return to the caller — each hit
        # converts the cached array once.
        results: List[Optional[List[float]]] = [None] * len(texts)

        # Pass 1: cache lookup under lock. Record hits directly into
        # ``results`` and remember which positions were misses.
        miss_indices: List[int] = []
        with self._lock:
            for i, key in enumerate(keys):
                cached = self._cache.get(key)
                if cached is not None:
                    # Touch for LRU ordering (recent access moves to end).
                    self._cache.move_to_end(key)
                    results[i] = cached.tolist()
                    self.hits += 1
                else:
                    miss_indices.append(i)

        if not miss_indices:
            # All hits — skip model entirely. Every slot was populated
            # under the lock above; direct return keeps the invariant.
            return results  # type: ignore[return-value]

        # Pass 2: dedup misses so identical-within-batch texts only
        # hit the underlying embedder once. ``key_to_positions`` maps
        # each unique missed key back to every index in ``texts`` that
        # asked for it.
        key_to_positions: "OrderedDict[str, List[int]]" = OrderedDict()
        unique_miss_texts: List[str] = []
        unique_miss_keys: List[str] = []
        for idx in miss_indices:
            key = keys[idx]
            if key not in key_to_positions:
                key_to_positions[key] = []
                unique_miss_texts.append(texts[idx])
                unique_miss_keys.append(key)
            key_to_positions[key].append(idx)

        # Pass 3: compute unique misses via the underlying embedder.
        # Runs OUTSIDE the lock — this is the slow part and holding
        # the lock across it would serialise unrelated cache accesses.
        new_vectors = self._wrapped.generate(unique_miss_texts)

        if len(new_vectors) != len(unique_miss_texts):
            # Defensive: the underlying contract is one vector per
            # input text. A mismatch would misalign cache keys.
            raise RuntimeError(
                f"Wrapped embedder returned {len(new_vectors)} vectors for "
                f"{len(unique_miss_texts)} inputs; cannot safely cache."
            )

        # Pass 4: populate cache + fan out vectors to every miss position.
        # ``misses`` counter is updated here (under the lock) so hits
        # and misses are maintained consistently — ``cache_stats`` sees
        # a coherent snapshot.
        with self._lock:
            self.misses += len(unique_miss_texts)
            for key, vec in zip(unique_miss_keys, new_vectors):
                # Compact float32 representation in the cache; the
                # public contract still returns ``list[float]``.
                self._cache[key] = np.asarray(vec, dtype=np.float32)
                # Bound the cache — evict the oldest entry if we're over.
                # ``popitem(last=False)`` is the LRU eviction (oldest end).
                while len(self._cache) > self._max_entries:
                    self._cache.popitem(last=False)
                for position in key_to_positions[key]:
                    results[position] = vec

        # Belt-and-braces: if a future bug ever leaves a position
        # unfilled, filtering with ``if vec is not None`` would silently
        # return a shorter list and misalign embeddings against chunks
        # downstream. Assert the invariant loudly instead — matches the
        # defensive posture of the wrapped-embedder length-mismatch
        # check above.
        assert all(v is not None for v in results), (
            f"internal: CachingEmbedder filled {sum(v is not None for v in results)}"
            f" of {len(results)} result positions for document batch"
        )
        return results  # type: ignore[return-value]

    def ndims(self) -> int:
        return self._wrapped.ndims()

    def cache_stats(self) -> dict:
        """Return a snapshot of cache stats. Useful for perf logging.

        Returns a dict with ``size`` (current entries), ``max_entries``,
        ``hits``, ``misses``, and ``hit_rate`` (float 0-1 or ``None``
        when no calls yet). Snapshot is taken under the lock so the
        numbers are consistent with each other.
        """
        with self._lock:
            total = self.hits + self.misses
            hit_rate = (self.hits / total) if total else None
            return {
                "size": len(self._cache),
                "max_entries": self._max_entries,
                "hits": self.hits,
                "misses": self.misses,
                "hit_rate": hit_rate,
            }
